### ISSUE TITLE
Working with WGS84

### ISSUE THREAD

**Issue by MarcM0** [open-navigation/opennav_coverage#61]
I am getting this error when running in iron `Internal Fields2Cover error: Geometry does not contain point 0` when I try to pass in a message in the wgs84 frame. 

```
        goal_msg = NavigateCompleteCoverage.Goal()
        goal_msg.frame_id = 'wgs84'
        goal_msg.polygons.append(self.toPolygon(field))

        print('Navigating to with field of size: ' + str(len(field)) + '...')
        send_goal_future = self.coverage_client.send_goal_async(goal_msg,
                                                                self._feedbackCallback)
        rclpy.spin_until_future_complete(self, send_goal_future)
        self.goal_handle = send_goal_future.result()
```

I saw some talk about this in https://github.com/Fields2Cover/Fields2Cover/issues/73 , but shouldnt it convert to meters once frameID is given?

Thanks in advance

**Comment by SteveMacenski** [comment]
That usually means you didn't populate the message properly. Check out unit tests, F2C examples for examples :smile:

**Comment by MarcM0** [comment]
I am passing the following [[-79.39132331041327, 43.63785348799382], [-79.39100734829563, 43.63703885671455], [-79.38967868708299, 43.63720295510174], [-79.38994603964407, 43.638023447037696], [-79.39132331041327, 43.63785348799382]] into these functions, which are identical to the demo, except that I added a frameid argument. 

```
def toPolygon(self, field):
        poly = Polygon()
        for coord in field:
            pt = Point32()
            pt.x = coord[0]
            pt.y = coord[1]
            poly.points.append(pt)
        return poly
    
    def navigateCoverage(self, field,frame_id):
        """Send a `NavToPose` action request."""
        print("Waiting for 'NavigateCompleteCoverage' action server")
        while not self.coverage_client.wait_for_server(timeout_sec=1.0):
            print('"NavigateCompleteCoverage" action server not available, waiting...')

        goal_msg = NavigateCompleteCoverage.Goal()
        goal_msg.frame_id = frame_id
        goal_msg.polygons.append(self.toPolygon(field))

        print('Navigating to with field of size: ' + str(len(field)) + '...')
        send_goal_future = self.coverage_client.send_goal_async(goal_msg,
                                                                self._feedbackCallback)
        rclpy.spin_until_future_complete(self, send_goal_future)
        self.goal_handle = send_goal_future.result()

        if not self.goal_handle.accepted:
            print('Navigate Coverage request was rejected!')
            return False

        self.result_future = self.goal_handle.get_result_async()
        return True

```
The goes away I pick a MUCH larger area

**Comment by SteveMacenski** [comment]
Are you properly setting the cartesian flags? This sounds like an issue with that: `coordinates_in_cartesian_frame`

**Comment by MarcM0** [comment]
I see, thanks, now I get Invalid GML File or Coordinates: Coordinate system not recognized
Here are my params
```
coverage_server:
  ros__parameters:
    use_sim_time: True
    default_headland_width: 0.25
    robot_width: 0.7
    operation_width: 0.7
    min_turning_radius: 0.35
    linear_curv_change: 200.0
    coordinates_in_cartesian_frame: false
    default_allow_overlap: false
    default_swath_angle_type: "SET_ANGLE"
    default_swath_angle: 0.0 # We know its aligned for the demo
```
