### ISSUE TITLE
Voids handling issue in humble branch

### ISSUE THREAD

**Issue by Jakubach** [open-navigation/opennav_coverage#70]
Hello,
I am using opennav_coverage from humble branch and recently I've noticed a problem with inner fields handling. I use polygons to specify coverage area. In the [F2C graphic](https://fields2cover.github.io/source/tutorials/route_planning.html), the scenario should look like (inner orange and red polygons are skipped):
![image](https://github.com/user-attachments/assets/99d9b01d-e5b6-467d-9d5b-f7f05bbd8078)

Below is the demonstration of the current behavior (the inner polygon is skipped but the planned path is still going through it):

https://github.com/user-attachments/assets/75ab543d-51d9-4b6f-b683-02e9069ba321

I am using below options:
```
coverage_server:
  ros__parameters:
    use_sim_time: True
    default_headland_width: 0.3
    robot_width: 0.525
    operation_width: 0.525
    min_turning_radius: 0.005
    linear_curv_change: 200.0
    coordinates_in_cartesian_frame: true
    default_allow_overlap: true
    default_swath_angle_type: "BRUTE_FORCE"
    default_swath_type: "NUMBER"
    default_step_angle: 0.261799 # radians (15 deg)
```
Is it related to the F2C version, configuration or something else and can it be resolved to handle static obstacles or disabled areas inside the covered field? Or the voids are not fully supported yet?
